### ISSUE TITLE
Add Permission to access External Storage

### ISSUE THREAD

**Issue by TUSHARZ** [TUSHARZ/BlogSpot#1]

**Comment by thilan7** [comment]
hi

**Comment by TUSHARZ** [comment]
You want to try it??

**Comment by thilan7** [comment]
yes. thankyou. 
please explain the issue :)

**Comment by TUSHARZ** [comment]
Its Basically a blogging app , in which you can add a title and image while you post , 
but in android lollipop and above it crashes as you require permissions to access external storage , so you just need to implement a function which asks for permission to access external storage , hope that helps you

**Comment by thilan7** [comment]
yes. that helps.  i have to research a little bit before starting this. thanks alot

**Comment by aldocano** [comment]
#3

**Comment by bacecek** [comment]
#4 Also added request permission on post screen.
